import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/next-theme.provider";
import { Toaster } from "sonner";
import ClientToaster from "@/components/ClientToaster";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "300","400","500","600","700","800","900", "1000"]
})


export const metadata: Metadata = {
  title: "كونترل الشمامسة",
  description: "Generated by St. Abader And Ereny His sister",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="ar" dir="rtl" suppressContentEditableWarning>
      <body
        className={`${cairo.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ClientToaster />
        </ThemeProvider>
      </body>
      
    </html>
    </>
  );
}
